export enum Services {
    BattleNet = 'battlenet',
    eBay = 'ebay',
    EpicGames = 'epicgames',
    Facebook = 'facebook',
    GitHub = 'github',
    Instagram = 'instagram',
    LeagueOfLegends = 'leagueoflegends',
    PayPal = 'paypal',
    PlayStation = 'playstation',
    Reddit = 'reddit',
    RiotGames = 'riotgames',
    Spotify = 'spotify',
    Skype = 'skype',
    Steam = 'steam',
    TikTok = 'tiktok',
    Twitch = 'twitch',
    Twitter = 'twitter',
    Xbox = 'xbox',
    YouTube = 'youtube',
}